name: "Build Image Robot"

on:
  push:
    branches: 
      - '*'
    paths:
      - dependencies/**
  workflow_dispatch:
  
env:
  CONTAINER_REGISTRY: pramotser
  IMAGE_NAME: robot-framework
  TAG_IMAGE_VERSION: "0.0.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        
      - name: "Docker Login"
        uses: docker/login-action@v1.10.0
        with: 
          registry: docker.io
          username: ${{ secrets.DCR_USERNAME }}
          password: ${{ secrets.DCR_PASSWORD }}
      
      - name: "Build Image Robot Framework"
        uses: docker/build-push-action@v2
        with:
          context: ./dependencies/
          file: dependencies/Dockerfile
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_IMAGE_VERSION }}
          push: false
          
      - name: "Push Image To Registry"
        run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_IMAGE_VERSION }}
