name: "Build Image Robot"

on:
  workflow_dispatch:
  
env:
  CONTAINER_REGISTRY: pramotser
  TAG_IMAGE: "0.0.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        
      - name: "Docker Login"
        uses: docker/login-action@v1.10.0
        with: 
          registry: docker.io
          username: ${{ secrets.DCR_USERNAME }}
          password: ${{ secrets.DCR_PASSWORD }}
      
      - name: "Build Image Robot Framework"
        uses: docker/build-push-action@v2
        with:
          context: ./dependencise/
          file: dependencies/Dockerfile
          tags: ${{ env.CONTAINER_REGISTRY }}/robot-framework:${{ env.TAG_IMAGE }}
