name: Hold Your Horses
on:
  pull_request:
    branches: 
      - master
  schedule:
    - cron: "* * * * *"

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Hold Your Horses
        uses: mheap/github-action-hold-your-horses@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          duration: "PT1H"
          trusted: mheap,other_user
          label_durations: bug=PT30M,feature=P1D